version: '3'
services:
  app:
    stdin_open: true
    tty: true
    image: container-fev4ple
    build:
      context: ./src
    ports:
      - "5000:8055"
    volumes:
      - type: bind
        source: ./src/web
        target: /usr/src/app
    environment:
      ALLOWED_HOSTS: "127.0.0.1,localhost"
      DEBUG: True
      SECRET_KEY: local_development
  directus:
    image: directus/directus:10.6.4
    ports:
      - "8055:8055"
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: 'replace-with-random-value'
      SECRET: 'replace-with-random-value'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/data.db'
      WEBSOCKETS_ENABLED: true
